# Generated by Django 2.0.8 on 2018-12-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20181215_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ask_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
