# Generated by Django 2.0.8 on 2018-09-17 23:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180917_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body2',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('date', wagtail.core.blocks.DateBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())]),
        ),
    ]
