# Generated by Django 2.0.8 on 2018-09-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogsectionpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsectionpage',
            old_name='intro',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='blogsectionpage',
            name='date',
        ),
    ]
