# Generated by Django 2.0.8 on 2018-09-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180923_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='post_date',
            field=models.DateField(blank=True, null=True, verbose_name='Post date'),
        ),
        migrations.AlterField(
            model_name='blogsectionpage',
            name='post_date',
            field=models.DateField(blank=True, null=True, verbose_name='Post date'),
        ),
    ]
