# Generated by Django 2.0.8 on 2018-09-27 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('blog', '0017_auto_20180926_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogsectionpage',
            name='intro',
            field=models.CharField(default='temporary text', max_length=250),
            preserve_default=False,
        ),
    ]
