# Generated by Django 2.0.8 on 2018-09-28 20:44

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailgeowidget.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180926_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('date', wagtail.core.blocks.DateBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('location', wagtailgeowidget.blocks.GeoBlock())]),
        ),
    ]
