# Generated by Django 2.0.8 on 2018-09-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180928_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='latlng_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
