# Generated by Django 2.0.8 on 2018-10-01 02:04

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20180928_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='location',
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('date', wagtail.core.blocks.DateBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock())]),
        ),
    ]
