# Generated by Django 2.0.8 on 2018-10-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('blog', '0024_auto_20181020_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloghomepage',
            name='q',
        ),
        migrations.AddField(
            model_name='bloghomepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
