# Generated by Django 2.0.8 on 2018-10-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20181023_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsectionpage',
            name='order',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
    ]
