# Generated by Django 2.0.8 on 2018-11-19 16:44

import blog.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailgeowidget.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20181117_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock())])), ('date', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock())])), ('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock())])), ('aside', wagtail.core.blocks.StructBlock([('aside', wagtail.core.blocks.BlockQuoteBlock())])), ('caption', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock())])), ('gallery', wagtail.core.blocks.StructBlock([('pictures', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))])), ('picture', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock())])), ('location', wagtail.core.blocks.StructBlock([('address', wagtail.core.blocks.CharBlock(required=False)), ('location', wagtailgeowidget.blocks.GeoBlock(address_field='address')), ('zoom', wagtail.core.blocks.IntegerBlock(default=8, max_value=19, min_value=0, required=False)), ('satellite', wagtail.core.blocks.BooleanBlock(required=False))])), ('place', wagtail.core.blocks.StructBlock([('place', wagtail.core.blocks.CharBlock(required=False)), ('location', blog.blocks.PlaceBlock(address_field='place')), ('zoom', wagtail.core.blocks.IntegerBlock(default=8, max_value=19, min_value=0, required=False)), ('satellite', wagtail.core.blocks.BooleanBlock(required=False))]))], blank=True, null=True),
        ),
    ]
