# Generated by Django 2.0.8 on 2018-12-08 17:31

import blog.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_bloghomepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloghomepage',
            name='body',
            field=wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock())])), ('date', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock())])), ('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock())])), ('aside', wagtail.core.blocks.StructBlock([('aside', wagtail.core.blocks.BlockQuoteBlock())])), ('caption', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock())])), ('gallery', wagtail.core.blocks.StructBlock([('pictures', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('date', wagtail.core.blocks.DateBlock(Required=False))])))])), ('picture', wagtail.core.blocks.StructBlock([('picture', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('date', wagtail.core.blocks.DateBlock(Required=False))]))])), ('location', wagtail.core.blocks.StructBlock([('address', wagtail.core.blocks.CharBlock(required=False)), ('place', wagtail.core.blocks.CharBlock(required=False)), ('location', blog.blocks.PlaceBlock(address_field='address', place_field='place')), ('zoom', wagtail.core.blocks.IntegerBlock(default=8, max_value=19, min_value=0, required=False)), ('satellite', wagtail.core.blocks.BooleanBlock(required=False)), ('date', wagtail.core.blocks.DateBlock(required=False))])), ('place', wagtail.core.blocks.StructBlock([('address', wagtail.core.blocks.CharBlock(required=False)), ('place', wagtail.core.blocks.CharBlock(required=False)), ('location', blog.blocks.PlaceBlock(address_field='address', place_field='place')), ('zoom', wagtail.core.blocks.IntegerBlock(default=8, max_value=19, min_value=0, required=False)), ('satellite', wagtail.core.blocks.BooleanBlock(required=False)), ('date', wagtail.core.blocks.DateBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock())])), ('date', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock())])), ('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock())])), ('aside', wagtail.core.blocks.StructBlock([('aside', wagtail.core.blocks.BlockQuoteBlock())])), ('caption', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock())])), ('gallery', wagtail.core.blocks.StructBlock([('pictures', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('date', wagtail.core.blocks.DateBlock(Required=False))])))])), ('picture', wagtail.core.blocks.StructBlock([('picture', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('date', wagtail.core.blocks.DateBlock(Required=False))]))])), ('location', wagtail.core.blocks.StructBlock([('address', wagtail.core.blocks.CharBlock(required=False)), ('place', wagtail.core.blocks.CharBlock(required=False)), ('location', blog.blocks.PlaceBlock(address_field='address', place_field='place')), ('zoom', wagtail.core.blocks.IntegerBlock(default=8, max_value=19, min_value=0, required=False)), ('satellite', wagtail.core.blocks.BooleanBlock(required=False)), ('date', wagtail.core.blocks.DateBlock(required=False))])), ('place', wagtail.core.blocks.StructBlock([('address', wagtail.core.blocks.CharBlock(required=False)), ('place', wagtail.core.blocks.CharBlock(required=False)), ('location', blog.blocks.PlaceBlock(address_field='address', place_field='place')), ('zoom', wagtail.core.blocks.IntegerBlock(default=8, max_value=19, min_value=0, required=False)), ('satellite', wagtail.core.blocks.BooleanBlock(required=False)), ('date', wagtail.core.blocks.DateBlock(required=False))]))], blank=True, null=True),
        ),
    ]
