# Generated by Django 2.0.8 on 2018-12-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_bloggallerypage_blogprojectpage_blogtrackerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogprojectpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogsectionpage',
            name='hide_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogsectionpage',
            name='hide_intro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogtrackerpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogtrackerpage',
            name='post_date',
            field=models.DateField(default='2018-12-08', verbose_name='Post date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloggallerypage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
