# Generated by Django 2.0.8 on 2018-12-10 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('blog', '0050_auto_20181208_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggallerypage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='bloggallerypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogprojectpage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='blogprojectpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogtrackerpage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='blogtrackerpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogGalleryPage',
        ),
        migrations.DeleteModel(
            name='BlogProjectPage',
        ),
        migrations.DeleteModel(
            name='BlogTrackerPage',
        ),
    ]
