# Generated by Django 2.0.8 on 2019-01-07 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailcore', '0040_page_draft_title'),
        ('blog', '0055_auto_20190107_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogemailpage',
            name='post_five',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_five_img_square',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_five_img_wide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_five_intro',
            field=models.CharField(default='post five', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_five_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_four_img_tall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_four_img_wide_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_four_img_wide_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_four_intro',
            field=models.CharField(default='post four', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_four_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_one_img_tall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_one_img_wide_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_one_img_wide_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_one_intro',
            field=models.CharField(default='post three', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_one_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_three_img_tall_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_three_img_tall_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_three_img_tall_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_three_intro',
            field=models.CharField(default='post two', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_three_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_two_img_wide_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_two_img_wide_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_two_intro',
            field=models.CharField(default='post one', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='post_two_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_four',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_two',
            field=models.BooleanField(default=False),
        ),
    ]
