# Generated by Django 2.0.8 on 2019-01-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_auto_20190107_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_five_intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_four_intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_one_intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_three_intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_two_intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
