# Generated by Django 2.0.8 on 2019-01-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_auto_20190107_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogemailpage',
            name='post_date',
        ),
        migrations.AddField(
            model_name='blogemailpage',
            name='sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sent date'),
        ),
    ]
