# Generated by Django 2.1.7 on 2019-03-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0075_auto_20190223_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogemailpage',
            name='intro',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_five_intro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_four_intro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_one_intro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_three_intro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_two_intro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
