# Generated by Django 2.1.7 on 2019-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0076_auto_20190315_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogemailpage',
            name='debug_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='intro',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_five_intro',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_four_intro',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_one_intro',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_three_intro',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogemailpage',
            name='post_two_intro',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
