# Generated by Django 2.1.7 on 2019-08-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_auto_20190812_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='search_key',
            field=models.CharField(default='***', max_length=24),
        ),
    ]
