# Generated by Django 2.1.7 on 2019-08-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0079_blogpostpage_search_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='search_key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
