# Generated by Django 2.2.4 on 2019-08-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0080_auto_20190818_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='insta_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='insta_instant',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
