# Generated by Django 2.2.4 on 2019-08-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0082_auto_20190826_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='insta_comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='insta_tags',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
