# Generated by Django 2.2.4 on 2019-08-29 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0083_auto_20190829_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='insta_comment',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.CreateModel(
            name='BlogInstaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('insta_flag', models.BooleanField(default=False)),
                ('insta_instant', models.DateTimeField(blank=True, null=True)),
                ('insta_comment', models.CharField(blank=True, max_length=2000, null=True)),
                ('insta_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
