# Generated by Django 2.2.4 on 2019-09-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0084_auto_20190829_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogemailpage',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
