# Generated by Django 2.2.4 on 2019-10-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0085_blogemailpage_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_per_post',
            field=models.BooleanField(default=False),
        ),
    ]
